/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as Auth_publicRouteImport } from './routes/_auth_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as OauthSuccessRouteImport } from './routes/oauth.success'
import { Route as OauthErrorRouteImport } from './routes/oauth.error'
import { Route as Auth_publicRegisterRouteImport } from './routes/_auth_public/register'
import { Route as Auth_publicLoginRouteImport } from './routes/_auth_public/login'
import { Route as Auth_publicInitPasswordForgetRouteImport } from './routes/_auth_public/init-password-forget'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as Auth_publicPasswordForgetTokenRouteImport } from './routes/_auth_public/password-forget.$token'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const Auth_publicRoute = Auth_publicRouteImport.update({
  id: '/_auth_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const OauthSuccessRoute = OauthSuccessRouteImport.update({
  id: '/oauth/success',
  path: '/oauth/success',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthErrorRoute = OauthErrorRouteImport.update({
  id: '/oauth/error',
  path: '/oauth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const Auth_publicRegisterRoute = Auth_publicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => Auth_publicRoute,
} as any)
const Auth_publicLoginRoute = Auth_publicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => Auth_publicRoute,
} as any)
const Auth_publicInitPasswordForgetRoute =
  Auth_publicInitPasswordForgetRouteImport.update({
    id: '/init-password-forget',
    path: '/init-password-forget',
    getParentRoute: () => Auth_publicRoute,
  } as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const Auth_publicPasswordForgetTokenRoute =
  Auth_publicPasswordForgetTokenRouteImport.update({
    id: '/password-forget/$token',
    path: '/password-forget/$token',
    getParentRoute: () => Auth_publicRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AuthDashboardRoute
  '/init-password-forget': typeof Auth_publicInitPasswordForgetRoute
  '/login': typeof Auth_publicLoginRoute
  '/register': typeof Auth_publicRegisterRoute
  '/oauth/error': typeof OauthErrorRoute
  '/oauth/success': typeof OauthSuccessRoute
  '/password-forget/$token': typeof Auth_publicPasswordForgetTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AuthDashboardRoute
  '/init-password-forget': typeof Auth_publicInitPasswordForgetRoute
  '/login': typeof Auth_publicLoginRoute
  '/register': typeof Auth_publicRegisterRoute
  '/oauth/error': typeof OauthErrorRoute
  '/oauth/success': typeof OauthSuccessRoute
  '/password-forget/$token': typeof Auth_publicPasswordForgetTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_auth_public': typeof Auth_publicRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth_public/init-password-forget': typeof Auth_publicInitPasswordForgetRoute
  '/_auth_public/login': typeof Auth_publicLoginRoute
  '/_auth_public/register': typeof Auth_publicRegisterRoute
  '/oauth/error': typeof OauthErrorRoute
  '/oauth/success': typeof OauthSuccessRoute
  '/_public/': typeof PublicIndexRoute
  '/_auth_public/password-forget/$token': typeof Auth_publicPasswordForgetTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/init-password-forget'
    | '/login'
    | '/register'
    | '/oauth/error'
    | '/oauth/success'
    | '/password-forget/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/init-password-forget'
    | '/login'
    | '/register'
    | '/oauth/error'
    | '/oauth/success'
    | '/password-forget/$token'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth_public'
    | '/_public'
    | '/_auth/dashboard'
    | '/_auth_public/init-password-forget'
    | '/_auth_public/login'
    | '/_auth_public/register'
    | '/oauth/error'
    | '/oauth/success'
    | '/_public/'
    | '/_auth_public/password-forget/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  Auth_publicRoute: typeof Auth_publicRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  OauthErrorRoute: typeof OauthErrorRoute
  OauthSuccessRoute: typeof OauthSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth_public': {
      id: '/_auth_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof Auth_publicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/oauth/success': {
      id: '/oauth/success'
      path: '/oauth/success'
      fullPath: '/oauth/success'
      preLoaderRoute: typeof OauthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/error': {
      id: '/oauth/error'
      path: '/oauth/error'
      fullPath: '/oauth/error'
      preLoaderRoute: typeof OauthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth_public/register': {
      id: '/_auth_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof Auth_publicRegisterRouteImport
      parentRoute: typeof Auth_publicRoute
    }
    '/_auth_public/login': {
      id: '/_auth_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof Auth_publicLoginRouteImport
      parentRoute: typeof Auth_publicRoute
    }
    '/_auth_public/init-password-forget': {
      id: '/_auth_public/init-password-forget'
      path: '/init-password-forget'
      fullPath: '/init-password-forget'
      preLoaderRoute: typeof Auth_publicInitPasswordForgetRouteImport
      parentRoute: typeof Auth_publicRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth_public/password-forget/$token': {
      id: '/_auth_public/password-forget/$token'
      path: '/password-forget/$token'
      fullPath: '/password-forget/$token'
      preLoaderRoute: typeof Auth_publicPasswordForgetTokenRouteImport
      parentRoute: typeof Auth_publicRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface Auth_publicRouteChildren {
  Auth_publicInitPasswordForgetRoute: typeof Auth_publicInitPasswordForgetRoute
  Auth_publicLoginRoute: typeof Auth_publicLoginRoute
  Auth_publicRegisterRoute: typeof Auth_publicRegisterRoute
  Auth_publicPasswordForgetTokenRoute: typeof Auth_publicPasswordForgetTokenRoute
}

const Auth_publicRouteChildren: Auth_publicRouteChildren = {
  Auth_publicInitPasswordForgetRoute: Auth_publicInitPasswordForgetRoute,
  Auth_publicLoginRoute: Auth_publicLoginRoute,
  Auth_publicRegisterRoute: Auth_publicRegisterRoute,
  Auth_publicPasswordForgetTokenRoute: Auth_publicPasswordForgetTokenRoute,
}

const Auth_publicRouteWithChildren = Auth_publicRoute._addFileChildren(
  Auth_publicRouteChildren,
)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  Auth_publicRoute: Auth_publicRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  OauthErrorRoute: OauthErrorRoute,
  OauthSuccessRoute: OauthSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
